taskboard
trapvpack/task-board pull request #1
Opened 2024-03-14 17:36 UTC by trapvpack

2024-04-03 17:51 UTC, SergeyShapovaIov requested changes

2024-04-03 17:51 UTC, ssh4rd commented on src/components/CardItemComponent/CardItem.scss
> +  }
Нужно удалить неиспользуемый селектор

2024-04-03 17:51 UTC, ssh4rd commented on src/components/CardItemComponent/CardItem.scss
> +  }
Здесь также нужно удалить

2024-04-03 17:51 UTC, ssh4rd commented on src/components/CardItemComponent/CardItem.vue
> +    type: Array<string>
Раз мы используем TypeScript, то лучше где-нибудь завести интерфейс карточки и использовать уже его

2024-04-03 17:51 UTC, SergeyShapovaIov commented on src/components/ColumnItemComponent/ColumnItem.html
> +      :cards="cards"
Зачем передавать в CardItem массив cards, если он там не используется?

2024-04-03 17:51 UTC, SergeyShapovaIov commented on src/components/ColumnItemComponent/ColumnItem.vue
> +}
Проверь правильно ли хранить описанную структуру в компоненте колонки, может вынести ее выше?

2024-04-03 17:51 UTC, SergeyShapovaIov commented on src/components/ColumnItemComponent/ColumnItem.vue
> +    type: Array<string>,
Вот здесь тоже лучше использовать свою структуру

2024-04-03 17:51 UTC, SergeyShapovaIov commented on src/components/StashComponent/Stash.html
> +      </svg>
svg можно вынести в отдельные файлы, а здесь только подключать. Так не будет дублированbя кода при использовании одинаковых svg. Возможно [тут](https://doka.guide/html/svg-sprite/) что-то найдешь

2024-04-03 17:51 UTC, SergeyShapovaIov commented on src/components/StashComponent/StashItem.vue
> +}
Как будто эти две функции можно объединить. Передавать в нее опцию закрыть/открыть, так не будет дублирования кода.

2024-04-03 17:51 UTC, SergeyShapovaIov commented on src/components/StashComponent/StashItem.vue
> +}
Вот это над этим тоже нужно подумать

2024-04-08 14:29 UTC, trapvpack commented on src/components/ColumnItemComponent/ColumnItem.vue
> +}
Можно вынести описанную структуру в отдельный файл, но мне кажется в данном случае это не имеет особого смысла, т.к. эта структура(интерфейс) описывает объект находящийся далеко внизу структуры программы, неиспользуемый на верхних уровнях.

2024-04-08 14:42 UTC, SergeyShapovaIov approved these changes

2024-04-08 14:43 UTC, merged